{
 "title": "env-shp-prod [CA-PROD] databases",
 "tags": [
  "memorystore",
  "postgres",
  "cloudsql",
  "env-shp-prod",
  "prod",
  "ca"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "redis" }
  ]
 },
 "panels": [
  { "title": "POSTGRES | idgital-production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transactions/sec on idgital CA db | Instances of main/r1/backup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production",
       "AND",
       "metric.label.database",
       "=",
       "idgital"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/postgresql/transaction_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-replica",
       "AND",
       "metric.label.database",
       "=",
       "idgital"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/postgresql/transaction_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-backup",
       "AND",
       "metric.label.database",
       "=",
       "idgital"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/postgresql/transaction_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Active connections  | Instances of CA main/r1/backup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "metric.label.database",
       "=",
       "idgital",
       "AND",
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/postgresql/num_backends",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-replica",
       "AND",
       "metric.label.database",
       "=",
       "idgital"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/postgresql/num_backends",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-backup",
       "AND",
       "metric.label.database",
       "=",
       "idgital"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/postgresql/num_backends",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "CPU utilization | Instances of CA main/r1/backup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-replica"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-backup"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/cpu/utilization",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Ingress/Egress bytes | Instances of CA main/r1/backup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-replica"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-replica"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-backup"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/network/received_bytes_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-backup"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk Read ops | Instances of CA main/r1/backup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/disk/read_ops_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-replica"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/disk/read_ops_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-backup"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/disk/read_ops_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Disk Write ops | Instances of CA main/r1/r2/replica-west",
   "type": "timeseries",
   "description": "main instance, read-replica-1, read-replica-2, replica-west",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/disk/write_ops_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-replica"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/disk/write_ops_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-backup"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/disk/write_ops_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Number of tuples (rows) in DB (live/dead) - CA MASTER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 33 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production",
       "AND",
       "metric.label.database",
       "=",
       "idgital",
       "AND",
       "metric.label.tuple_state",
       "=",
       "live"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/postgresql/tuple_size",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "metric.label.database",
       "=",
       "idgital",
       "AND",
       "metric.label.tuple_state",
       "=",
       "dead",
       "AND",
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/postgresql/tuple_size",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Deadlocks count on whole CA PROD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 41 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production"
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "cloudsql.googleapis.com/database/postgresql/deadlock_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Memory usage / Memory Quota  on CA MASTER",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/memory/usage",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/memory/quota",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Memory usage / Memory Quota  on replica-1 CA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-replica"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/memory/usage",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-replica"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/memory/quota",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Memory usage / Memory Quota  on backup CA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 57 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-backup"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/memory/usage",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-replica"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/memory/quota",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Storage usage / Storage Quota  on CA Master",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/bytes_used",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/quota",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Storage usage / Storage Quota  on replica-1 CA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-replica"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/bytes_used",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-replica"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/quota",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Storage usage / Storage Quota  on backup CA",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 73 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-backup"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/bytes_used",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "resource.label.database_id",
       "=",
       "env-shp-prod:idgital-production-backup"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "cloudsql.googleapis.com/database/disk/quota",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "MEMORYSTORE | speech-to-text",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/server/uptime",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/usage",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/maxmemory",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Keys in database / Evicted keys / Expired keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/evicted_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/expired_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Average TTL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/avg_ttl",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/cache_hit_ratio",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Connected clients / Blocked clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/connected",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/blocked",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Total connections / Rejected connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/connections/total",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/reject_connections_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/cpu_utilization",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Calls/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/commands/calls",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "MEMORYSTORE | idg-redis-ca-prod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/server/uptime",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Average TTL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/avg_ttl",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Keys in database / Evicted keys / Expired keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/evicted_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/expired_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Connected clients / Blocked clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/connected",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/blocked",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/cache_hit_ratio",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Memory Usage / Max memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/usage",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/maxmemory",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Total connections / Rejected connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/connections/total",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/reject_connections_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/cpu_utilization",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Calls/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/commands/calls",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "MEMORYSTORE | idg-redis-notification-ca-prod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-notification-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/server/uptime",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Average TTL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-notification-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/avg_ttl",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Keys in database / Evicted keys / Expired keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/evicted_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/expired_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Connected clients / Blocked clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-notification-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/connected",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-notification-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/blocked",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/cache_hit_ratio",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Memory Usage / Max memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-notification-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/usage",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-notification-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/maxmemory",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Total connections / Rejected connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-notification-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/connections/total",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-notification-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/reject_connections_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-notification-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/cpu_utilization",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Calls/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-notification-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/commands/calls",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "MEMORYSTORE | idg-redis-cache-ca-prod ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/server/uptime",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Average TTL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-cache-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/avg_ttl",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Connected clients / Blocked clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-cache-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/connected",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-cache-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/blocked",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Memory Usage / Max memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-cache-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/usage",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-cache-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/maxmemory",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Keys in database / Evicted keys / Expired keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-cache-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-cache-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/evicted_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-cache-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/expired_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-cache-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/cpu_utilization",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-cache-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/cache_hit_ratio",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Calls/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-cache-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/commands/calls",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Total connections / Rejected connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-cache-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/connections/total",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "env-shp-prod",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/env-shp-prod/locations/northamerica-northeast1/instances/idg-redis-cache-ca-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/reject_connections_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    }
   ]
  }
 ]
}