{
 "title": "idg-platform [US PROD] databases",
 "tags": [
  "memorystore",
  "postgres",
  "cloudsql",
  "prod",
  "us",
  "idg-platform"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": "redis" }
  ]
 },
 "panels": [
  {
   "title": "POSTGRES | idgital-production",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions/sec on idgital db | Instances of main/r1/r2/replica-west",
     "type": "timeseries",
     "description": "main instance, read-replica-1, read-replica-2, replica-west",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production",
         "AND",
         "metric.label.database",
         "=",
         "idgital"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/postgresql/transaction_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica1",
         "AND",
         "metric.label.database",
         "=",
         "idgital"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/postgresql/transaction_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica2",
         "AND",
         "metric.label.database",
         "=",
         "idgital"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/postgresql/transaction_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica-west",
         "AND",
         "metric.label.database",
         "=",
         "idgital"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/postgresql/transaction_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Active connections  | Instances of main/r1/r2/replica-west",
     "type": "timeseries",
     "description": "main instance, read-replica-1, read-replica-2, replica-west",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "metric.label.database",
         "=",
         "idgital",
         "AND",
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/postgresql/num_backends",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica1",
         "AND",
         "metric.label.database",
         "=",
         "idgital"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/postgresql/num_backends",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica2",
         "AND",
         "metric.label.database",
         "=",
         "idgital"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/postgresql/num_backends",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica-west",
         "AND",
         "metric.label.database",
         "=",
         "idgital"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/postgresql/num_backends",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "CPU utilization | Instances of main/r1/r2/replica-west",
     "type": "timeseries",
     "description": "main instance, read-replica-1, read-replica-2, replica-west",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/cpu/utilization",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica1"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/cpu/utilization",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica2"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/cpu/utilization",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica-west"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/cpu/utilization",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Ingress/Egress bytes | Instances of main/r1/r2/replica-west",
     "type": "timeseries",
     "description": "main instance, read-replica-1, read-replica-2, replica-west",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/network/received_bytes_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/network/sent_bytes_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica1"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/network/received_bytes_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica1"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/network/sent_bytes_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica2"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/network/received_bytes_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica2"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/network/sent_bytes_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica-west"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/network/received_bytes_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica-west"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/network/sent_bytes_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Disk Read ops | Instances of main/r1/r2/replica-west",
     "type": "timeseries",
     "description": "main instance, read-replica-1, read-replica-2, replica-west",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/disk/read_ops_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica1"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/disk/read_ops_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica2"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/disk/read_ops_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica-west"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/disk/read_ops_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Disk Write ops | Instances of main/r1/r2/replica-west",
     "type": "timeseries",
     "description": "main instance, read-replica-1, read-replica-2, replica-west",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/disk/write_ops_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica1"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/disk/write_ops_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica2"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/disk/write_ops_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica-west"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/disk/write_ops_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Number of tuples (rows) in DB (live/dead) - MASTER",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 33 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production",
         "AND",
         "metric.label.database",
         "=",
         "idgital",
         "AND",
         "metric.label.tuple_state",
         "=",
         "live"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/postgresql/tuple_size",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "metric.label.database",
         "=",
         "idgital",
         "AND",
         "metric.label.tuple_state",
         "=",
         "dead",
         "AND",
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/postgresql/tuple_size",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Deadlocks count on whole PROD",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 41 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/postgresql/deadlock_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Memory usage / Memory Quota  on MASTER",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/memory/usage",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/memory/quota",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Memory usage / Memory Quota  on replica-1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica1"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/memory/usage",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica1"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/memory/quota",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Memory usage / Memory Quota  on replica-2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica2"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/memory/usage",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica2"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/memory/quota",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Memory usage / Memory Quota  on replica-west",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica-west"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/memory/usage",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica-west"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/memory/quota",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Storage usage / Storage Quota  on Master",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/disk/bytes_used",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/disk/quota",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Storage usage / Storage Quota  on replica-1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica1"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/disk/bytes_used",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica1"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/disk/quota",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Storage usage / Storage Quota  on replica-2",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica2"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/disk/bytes_used",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica2"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/disk/quota",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Storage usage / Storage Quota  on replica-west",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica-west"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/disk/bytes_used",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-production-replica-west"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/disk/quota",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "POSTGRES | idgital-playbook",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions/sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "metric.label.database",
         "=",
         "playbook"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/postgresql/transaction_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Active connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-playbook"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/postgresql/num_backends_by_state",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "CPU utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-playbook"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/cpu/utilization",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Storage usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-playbook"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/disk/bytes_used",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-playbook"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/disk/quota",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Memory usage / Memory Quota",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-playbook"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/memory/usage",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-playbook"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "cloudsql.googleapis.com/database/memory/quota",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Disk read/write ops",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-playbook"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/disk/read_ops_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-playbook"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/disk/write_ops_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Ingress/egress bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-playbook"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/network/received_bytes_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.database_id",
         "=",
         "idg-platform:idgital-playbook"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "cloudsql.googleapis.com/database/network/sent_bytes_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "MEMORYSTORE | speech-to-text",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/server/uptime",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/usage",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/maxmemory",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Keys in database / Evicted keys / Expired keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/evicted_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/expired_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Average TTL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/avg_ttl",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/cache_hit_ratio",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Connected clients / Blocked clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/connected",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/blocked",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Total connections / Rejected connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/connections/total",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/reject_connections_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "CPU utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/cpu_utilization",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Calls/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/speech-to-text"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/commands/calls",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "MEMORYSTORE | idg-redis-prod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/server/uptime",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Average TTL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/avg_ttl",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Keys in database / Evicted keys / Expired keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/evicted_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/expired_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Connected clients / Blocked clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/connected",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/blocked",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/cache_hit_ratio",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Memory Usage / Max memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/usage",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/maxmemory",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Total connections / Rejected connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/connections/total",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/reject_connections_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/cpu_utilization",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Calls/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/commands/calls",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "MEMORYSTORE | idg-redis-notification-prod",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-notification-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/server/uptime",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Average TTL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-notification-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/avg_ttl",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Keys in database / Evicted keys / Expired keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "notification-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-notification-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/evicted_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-notification-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/expired_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Connected clients / Blocked clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-notification-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/connected",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-notification-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/blocked",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-notification-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/cache_hit_ratio",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Memory Usage / Max memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-notification-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/usage",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-notification-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/maxmemory",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Total connections / Rejected connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-notification-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/connections/total",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-notification-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/reject_connections_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-notification-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/cpu_utilization",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Calls/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-notification-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/commands/calls",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "MEMORYSTORE | idg-redis-cache-prod-instance2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-instance2"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/server/uptime",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Average TTL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-instance2"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/avg_ttl",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Keys in database / Evicted keys / Expired keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-instance2"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-instance2"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/evicted_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-instance2"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/expired_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Memory Usage / Max memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-instance2"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/usage",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-instance2"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/maxmemory",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-instance2"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/cache_hit_ratio",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Connected clients / Blocked clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-instance2"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/connected",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-instance2"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/blocked",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Total connections / Rejected connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-instance2"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/connections/total",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-instance2"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/reject_connections_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-instance2"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/cpu_utilization",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Calls/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-instance2"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/commands/calls",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "MEMORYSTORE | idg-redis-cache-prod-bkp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-bkp"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/server/uptime",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Average TTL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-bkp"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/avg_ttl",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Keys in database / Evicted keys / Expired keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-bkp"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-bkp"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/evicted_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-bkp"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/expired_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Memory Usage / Max memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-bkp"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/usage",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-bkp"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/maxmemory",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-bkp"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/cache_hit_ratio",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Connected clients / Blocked clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-bkp"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/connected",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-bkp"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/blocked",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Total connections / Rejected connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-bkp"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/connections/total",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-bkp"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/reject_connections_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-bkp"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/cpu_utilization",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Calls/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod-bkp"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/commands/calls",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "MEMORYSTORE | idg-redis-cache-prod ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/server/uptime",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Average TTL",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/avg_ttl",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Connected clients / Blocked clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/connected",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/clients/blocked",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Memory Usage / Max memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/usage",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/memory/maxmemory",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Keys in database / Evicted keys / Expired keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/keyspace/keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/evicted_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/expired_keys",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "CPU seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/cpu_utilization",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "redis.googleapis.com/stats/cache_hit_ratio",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Calls/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/commands/calls",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Total connections / Rejected connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/connections/total",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.instance_id",
         "=",
         "projects/idg-platform/locations/us-central1/instances/idg-redis-cache-prod"
        ],
        "groupBys": [],
        "metricKind": "DELTA",
        "metricType": "redis.googleapis.com/stats/reject_connections_count",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "rate",
        "projectName": "idg-platform",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    }
   ]
  }
 ]
}