{
 "title": "Mirth Channel Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "channel", "label": "channel", "query": { "query": "synthflow_hl7_errored_messages" } },
   {
    "name": "environment",
    "label": "environment",
    "query": {
     "query": "{__name__=~\"synthflow_.*\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Queued Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synthflow_hl7_queued_messages{channel_name=\"$channel\", env_name=\"$environment\", server_name=\"Mirth Hub\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued Messages Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum by (hour)(synthflow_hl7_queued_messages{channel_name=\"$channel\", env_name=\"$environment\", server_name=\"Mirth Hub\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Error Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synthflow_hl7_errored_messages{channel_name=\"$channel\", env_name=\"$environment\", server_name=\"Mirth Hub\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Messages Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 7, "y": 6 },
   "targets": [
    {
     "expr": "sum by (hour)(synthflow_hl7_errored_messages{channel_name=\"$channel\", env_name=\"$environment\", server_name=\"Mirth Hub\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Recieved Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synthflow_hl7_recieved_messages{channel_name=\"$channel\", env_name=\"$environment\", server_name=\"Mirth Hub\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recieved Messages Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 7, "y": 12 },
   "targets": [
    {
     "expr": "sum by (hour)(synthflow_hl7_recieved_messages{channel_name=\"$channel\", env_name=\"$environment\", server_name=\"Mirth Hub\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synthflow_hl7_sent_messages{channel_name=\"$channel\", env_name=\"$environment\", server_name=\"Mirth Hub\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Messages Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 7, "y": 18 },
   "targets": [
    {
     "expr": "sum by (hour)(synthflow_hl7_sent_messages{channel_name=\"$channel\", env_name=\"$environment\", server_name=\"Mirth Hub\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Filtered Messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "synthflow_hl7_filter_messages{channel_name=\"$channel\", env_name=\"$environment\", server_name=\"Mirth Hub\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filtered Messages Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 7, "y": 24 },
   "targets": [
    {
     "expr": "sum by (hour)(synthflow_hl7_filter_messages{channel_name=\"$channel\", env_name=\"$environment\", server_name=\"Mirth Hub\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}