{
 "title": "Project Cost Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Service Cost",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "location": "US",
     "project": "idg-prod-bigquery",
     "rawSql": "SELECT service.description as service, currency, sum(cost) AS cost\r\nFROM `idg_gcp_costs.gcp_billing_export_v1_*`\r\nWHERE cast(usage_start_time as date ) >= (SELECT DATE_TRUNC(CURRENT_DATETIME(), MONTH))\r\nGROUP BY service, currency\r\nORDER BY cost DESC"
    }
   ]
  },
  {
   "title": "Total Cost",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "idg-prod-bigquery",
     "rawSql": "Select sum(cost) AS cost FROM `idg_gcp_costs.gcp_billing_export_v1_*`\r\nWHERE cast(usage_start_time as date ) >= (SELECT DATE_TRUNC(CURRENT_DATETIME(), MONTH))\r\n"
    }
   ]
  },
  {
   "title": "Project Wise Cost",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "location": "US",
     "project": "idg-prod-bigquery",
     "rawSql": "SELECT project.name as project, currency, sum(cost) AS cost\r\nFROM `idg_gcp_costs.gcp_billing_export_v1_*`\r\nWHERE cast(usage_start_time as date ) >= (SELECT DATE_TRUNC(CURRENT_DATETIME(), MONTH))\r\nGROUP BY project, currency\r\nORDER BY cost DESC"
    }
   ]
  },
  {
   "title": "Projects Last 6 Months Cost",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "project": "idg-prod-bigquery",
     "rawSql": "SELECT * FROM\r\n( SELECT project.name as project, currency, EXTRACT(MONTH FROM usage_start_time) monthval, sum(cost) AS cost\r\n FROM `idg_gcp_costs.gcp_billing_export_v1_*`\r\n WHERE cast(usage_start_time as date ) >= (SELECT DATE_TRUNC(date_add(CURRENT_DATETIME(),INTERVAL -6 MONTH), MONTH))\r\n GROUP BY project, currency, EXTRACT(MONTH FROM usage_start_time))\r\n   PIVOT(SUM(cost) FOR monthval IN (1, 2, 3, 4, 5, 6))"
    }
   ]
  },
  {
   "title": "Service Cost 6 Months",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "location": "US",
     "project": "idg-prod-bigquery",
     "rawSql": "SELECT * FROM\r\n( SELECT service.description as service, currency, EXTRACT(MONTH FROM usage_start_time) monthval, sum(cost) AS cost\r\n FROM `idg_gcp_costs.gcp_billing_export_v1_*`\r\n WHERE cast(usage_start_time as date ) >= (SELECT DATE_TRUNC(date_add(CURRENT_DATETIME(),INTERVAL -6 MONTH), MONTH))\r\n GROUP BY service, currency, EXTRACT(MONTH FROM usage_start_time))\r\n   PIVOT(SUM(cost) FOR monthval IN (1, 2, 3, 4, 5, 6))"
    }
   ]
  }
 ]
}