{
 "title": "Uptime checkers",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "PRD - Overall | ALERT DASH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [
       "metric.label.instance_name",
       "=",
       ""
      ],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/uptime",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "idg-platform",
      "query": "",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "PRD (Canada) - Overrall | ALERT DASH",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "compute.googleapis.com/instance/uptime",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "env-shp-prod",
      "query": "",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Eunity - Overall - PRD",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stackdriver_gce_instance_compute_googleapis_com_instance_uptime{instance_name=~\"eunity-standalone-v2|eunity-standalone-group-8qjn|eunity-secondary-group-9xg1|eunity-primary-node|eunity-standalone|eunity-standalone-v1|eunity-standalone-primary-node|eunity3d-rendering|eunity3d-edge|eunity3d-data\"}"
    }
   ]
  },
  {
   "title": "Eunity - Stage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stackdriver_gce_instance_compute_googleapis_com_instance_uptime{instance_name=\"eunity-primary-node\"}"
    }
   ]
  },
  {
   "title": "Speech-to-text - PRD",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stackdriver_gce_instance_compute_googleapis_com_instance_uptime{instance_name=\"speech-to-text-vm-prod\"}"
    }
   ]
  },
  {
   "title": "Speech-to-text - CA PRD",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stackdriver_gce_instance_compute_googleapis_com_instance_uptime{instance_name=\"speech-to-text-vm-ca-prod\"}"
    }
   ]
  },
  {
   "title": "Speech-to-text - Stage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stackdriver_gce_instance_compute_googleapis_com_instance_uptime{instance_name=\"speech-to-text-vm-stage\"}"
    }
   ]
  }
 ]
}