{
 "title": "Micro Service Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Reqeust",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{container=\"$container\", uri!~\"/health|/prometheus|/swagger/.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_client_requests_seconds_sum{container=\"$container\", uri!~\"/health|/prometheus|/swagger/.*\"}) / sum(http_client_requests_seconds_count{container=\"$container\", uri!~\"/health|/prometheus|/swagger/.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Instance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{container=\"$container\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{container=\"$container\", uri!~\"/health|/prometheus|/swagger/.*\"}) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inbound Graph",
   "type": "nodeGraph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "serviceMapQuery": "{server=\"$container\"}"
    }
   ]
  },
  {
   "title": "Outbound Graph",
   "type": "nodeGraph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "serviceMapQuery": "{client=\"$container\"}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri)(http_server_requests_seconds_sum{container=\"$container\", uri!~\"/health|/prometheus|/swagger/.*\"}) / sum by(uri)(http_server_requests_seconds_count{container=\"$container\", uri!~\"/health|/prometheus|/swagger/.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Per Second(RPS)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri)(rate(http_server_requests_seconds_count{container=\"$container\", uri!~\"/health|/prometheus|/swagger/.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_max{container=\"$container\", uri!~\"/health|/prometheus|/swagger/.*\"}) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{container=\"$container\", uri!~\"/health|/prometheus|/swagger/.*\", status=\"200\"}) / sum by(uri) (http_server_requests_seconds_count{container=\"$container\", uri!~\"/health|/prometheus|/swagger/.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of 5xx/4xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{container=\"$container\", uri!~\"/health|/prometheus|/swagger/.*\", status=~\"4.*|5.*\"}) / sum by(uri) (http_server_requests_seconds_count{container=\"$container\", uri!~\"/health|/prometheus|/swagger/.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by(severity) (rate({container=\"$container\"} | json severity | __error__=\"\" [1m]))"
    }
   ]
  },
  {
   "title": "Latest Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 52 },
   "targets": [
    {
     "expr": "{container=\"$container\"} | json severity, message | line_format `{{ .severity }} ----> {{ .message }}`"
    }
   ]
  },
  {
   "title": "Latest Error Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logback_events_total{container=\"$container\", level=\"error\"})"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 61 },
   "targets": [
    {
     "expr": "{container=\"$container\"} | json severity, message | severity = `ERROR` | line_format `{{ .severity}} --> {{ .message }}`"
    }
   ]
  },
  {
   "title": "Latest Warning Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(logback_events_total{container=\"$container\", level=\"warn\"})"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 70 },
   "targets": [
    {
     "expr": "{container=\"$container\"} | json severity, message | severity = `WARN` | line_format `{{ .severity}} --> {{ .message }}`"
    }
   ]
  }
 ]
}