{
 "title": "Micro-service Instance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "query": {
     "query": "label_values(http_server_requests_seconds_count, container)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(process_uptime_seconds{container=\"$application\"}, pod)"
    }
   },
   {
    "name": "heap_pool",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{container=\"$application\", pod=\"$pod\", area=\"heap\"},id)"
    }
   },
   {
    "name": "non_heap_pool",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{container=\"$application\", pod=\"$pod\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{container=\"$application\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{container=\"$application\", pod=\"$pod\"}*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{container=\"$application\", pod=\"$pod\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{container=\"$application\",pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-heap Used",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{container=\"$application\", pod=\"$pod\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{container=\"$application\",pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Request Per Second(RPS)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{container=\"$application\", pod=\"$pod\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{container=\"$application\", pod=\"$pod\", status!~\"5..\"}[1m])) by (uri) /sum(rate(http_server_requests_seconds_count{container=\"$application\", pod=\"$pod\", status!~\"5..\"}[1m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_server_requests_seconds_count{container=\"$application\", pod=\"$pod\", status=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "JVM Total Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{container=\"$application\", pod=\"$pod\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{container=\"$application\", pod=\"$pod\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{container=\"$application\", pod=\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{container=\"$application\", pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{container=\"$application\", pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{container=\"$application\", pod=\"$pod\", area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{container=\"$application\", pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{container=\"$application\", pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{container=\"$application\", pod=\"$pod\", area=\"nonheap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{container=\"$application\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_cpu_usage{container=\"$application\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{container=\"$application\", pod=\"$pod\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "system_load_average_1m{container=\"$application\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{container=\"$application\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_threads_daemon_threads{container=\"$application\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_threads_peak_threads{container=\"$application\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread State",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{container=\"$application\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log Events Per Min",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "increase(logback_events_total{container=\"$application\", pod=\"$pod\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File Descriptor",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_files_open_files{container=\"$application\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_files_max_files{container=\"$application\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM Heap Memory Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "$heap_pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "repeat": "heap_pool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{container=\"$application\", pod=\"$pod\", id=~\"$heap_pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_committed_bytes{container=\"$application\", pod=\"$pod\", id=~\"$heap_pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_max_bytes{container=\"$application\", pod=\"$pod\", id=~\"$heap_pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "JVM Non-Heap Memory Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "$non_heap_pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 51 },
   "repeat": "non_heap_pool",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{container=\"$application\", pod=\"$pod\", id=~\"$non_heap_pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_committed_bytes{container=\"$application\", pod=\"$pod\", id=~\"$non_heap_pool\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_memory_max_bytes{container=\"$application\", pod=\"$pod\", id=~\"$non_heap_pool\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "GC OPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{container=\"$application\", pod=\"$pod\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{container=\"$application\", pod=\"$pod\"}[1m])/rate(jvm_gc_pause_seconds_count{container=\"$application\", pod=\"$pod\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Pause Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_max{container=\"$application\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Class Loading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Classes Loaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{container=\"$application\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Loaded Classes Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{container=\"$application\",pod=\"$pod\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Direct Buffers Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{container=\"$application\", pod=\"$pod\", id=\"direct\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{container=\"$application\", pod=\"$pod\", id=\"direct\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Direct Buffer Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{container=\"$application\", pod=\"$pod\", id=\"direct\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mapped Buffers Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{container=\"$application\", pod=\"$pod\", id=\"mapped\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{container=\"$application\", pod=\"$pod\", id=\"mapped\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mapped Buffer Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 86 },
   "targets": [
    {
     "expr": "jvm_buffer_count_buffers{container=\"$application\", pod=\"$pod\", id=\"mapped\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}